version: '3'

services:
    nodejs-app:
        build:
          context: ./nodedocker_app
        restart: always
        container_name: nodejsserver
        hostname: nodejsserver
        ports:
            - "3347:3347" 
        networks:
            - mail-service-net

networks:
  mail-service-net:
    external:
      name: mail-service-net
     
