version: '3'

services:
    nodejs-app:
        build:
          context: ./nodedocker_app
        restart: always
        container_name: nodejsserver
        hostname: nodejsserver
        ports:
            - "3347:3347" 
        networks:
            - mail-service-net  
    nginx:
        build:
          context: ./nginx
        restart: always
        container_name: nginx
        hostname: nginx
        ports:
            - "80:80" 
        depends_on:
            - nodejs-app
        networks:
            - mail-service-net

networks:
  mail-service-net:
    external: true
